### ISSUE TITLE
file doesn't exist while run python3 dm_nn_stack.py

### ISSUE THREAD

**Issue by SeekPoint** [hengchao0248/ccf2016_sougou#1]
04
/usr/local/lib/python3.4/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5105)
/usr/local/lib/python3.4/dist-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Using Theano backend.
Traceback (most recent call last):
  File "dm_nn_stack.py", line 24, in <module>
    df_all = pd.read_csv(cfg.data_path + 'all.csv',encoding='utf8',usecols=['Id','Education','age','gender'],nrows=200000)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4025)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8031)
FileNotFoundError: File b'./data/all.csv' does not exist
05
Traceback (most recent call last):
  File "xgb_ens.py", line 15, in <module>
    df_dm = pd.read_csv(cfg.data_path + 'dmd2v_stack_20W.csv')
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 645, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 388, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 729, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 922, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.4/dist-packages/pandas/io/parsers.py", line 1389, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4025)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8031)
FileNotFoundError: File b'./data/dmd2v_stack_20W.csv' does not exist
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ 
rzai@rzai00:~/prj/ccf2016_sougou$ tree
.
├── alldata-id-shuf.txt
├── alldata-id.txt
├── cfg.py
├── cfg.pyc
├── data
│   ├── all_v2.csv
│   ├── dbow_d2v.model
│   ├── dbow_d2v.model.docvecs.doctag_syn0.npy
│   ├── dbow_d2v.model.syn0.npy
│   ├── dbow_d2v.model.syn1neg.npy
│   ├── dbowd2v_stack_20W.csv
│   ├── dm_d2v.model
│   ├── dm_d2v.model.docvecs.doctag_syn0.npy
│   ├── dm_d2v.model.syn0.npy
│   ├── dm_d2v.model.syn1neg.npy
│   ├── tfidf_10W.feat
│   ├── tfidf_stack_20W.csv
│   ├── user_tag_query.10W.TEST
│   └── user_tag_query.10W.TRAIN
├── dbow_nn_stack.py
├── dm_nn_stack.py
├── docs
│   └── 队旗.jpg
├── fill_nan.py
├── __pycache__
│   └── cfg.cpython-34.pyc
├── README.md
├── run_cv.ipynb
├── run.sh
├── sougou_from_pan.baidu.zip
├── tfidf_lr_stack.py
├── train_d2v_model.py
└── xgb_ens.py

3 directories, 30 files
rzai@rzai00:~/prj/ccf2016_sougou$

**Comment by hengchao0248** [comment]
thank you for  reminding,I have fixed this bug,please run scripts again.
